<?php

namespace Database\Factories;

use App\Models\User;
use App\Models\SavingsAccount;
use App\Models\LoanAccount;
use App\Models\ShareAccount;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Account>
 */
class AccountFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition()
    {
        $status = $this->faker->randomElement(['active', 'inactive', 'dormant', 'closed']);

        // Use existing user or create one
        $member = User::inRandomOrder()->first() ?? User::factory()->create();

        // Pick a random accountable type and use existing record
        $accountableType = $this->faker->randomElement([
            SavingsAccount::class,
            LoanAccount::class,
            ShareAccount::class,
        ]);

        $accountable = match($accountableType) {
            SavingsAccount::class => SavingsAccount::inRandomOrder()->first() ?? SavingsAccount::factory()->create(),
            LoanAccount::class => LoanAccount::inRandomOrder()->first() ?? LoanAccount::factory()->create(),
            ShareAccount::class => ShareAccount::inRandomOrder()->first() ?? ShareAccount::factory()->create(),
        };

        return [
            // account_number is auto-generated by model boot() method
            'member_id' => $member->id,
            'accountable_type' => $accountableType,
            'accountable_id' => $accountable->id,
            'status' => $status,
            'closure_reason' => $status === 'closed' ? $this->faker->sentence() : null,
            'closed_at' => $status === 'closed' ? now() : null,
            'closed_by' => $status === 'closed' ? ($member->id ?? null) : null,
            'last_transaction_date' => $this->faker->optional()->dateTimeBetween('-3 months'),
            'opening_date' => $this->faker->dateTimeBetween('-2 years', '-1 month'),
        ];
    }

    /**
     * Create account with a savings account
     */
    public function withSavingsAccount(?SavingsAccount $savingsAccount = null): static
    {
        return $this->state(function (array $attributes) use ($savingsAccount) {
            $savings = $savingsAccount ?? SavingsAccount::inRandomOrder()->first() ?? SavingsAccount::factory()->create();

            return [
                'accountable_type' => SavingsAccount::class,
                'accountable_id' => $savings->id,
            ];
        });
    }

    /**
     * Create account with a loan account
     */
    public function withLoanAccount(?LoanAccount $loanAccount = null): static
    {
        return $this->state(function (array $attributes) use ($loanAccount) {
            $loan = $loanAccount ?? LoanAccount::inRandomOrder()->first() ?? LoanAccount::factory()->create();

            return [
                'accountable_type' => LoanAccount::class,
                'accountable_id' => $loan->id,
            ];
        });
    }

    /**
     * Create account with a share account
     */
    public function withShareAccount(?ShareAccount $shareAccount = null): static
    {
        return $this->state(function (array $attributes) use ($shareAccount) {
            $share = $shareAccount ?? ShareAccount::inRandomOrder()->first() ?? ShareAccount::factory()->create();

            return [
                'accountable_type' => ShareAccount::class,
                'accountable_id' => $share->id,
            ];
        });
    }

    /**
     * Create active account (convenience method)
     */
    public function active(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'active',
            'closure_reason' => null,
            'closed_at' => null,
            'closed_by' => null,
        ]);
    }

    /**
     * Create closed account (convenience method)
     */
    public function closed(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'closed',
            'closure_reason' => $this->faker->sentence(),
            'closed_at' => now(),
            'closed_by' => User::inRandomOrder()->first()?->id ?? User::factory()->create()->id,
        ]);
    }
}
